config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'users#new'
  get 'users/new'

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/github', as: 'github_login'
  get 'logout' => 'sessions#destroy'

  match 'auth/facebook/callback', to: 'sessions#fbcreate', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#fbdestroy', as: 'signout', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, presence: true

  def self.create_from_github(auth)
    User.create!(
      github_id: auth['uid'],
      name: auth['info']['name'],
      email: auth['info']['email']
    )
    end

    def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
    end
  end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    private

    # make this method accessible in any controller
    def current_user
      # memoization (caching) technique
      # multiple calls to this method will result in only one database query
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    # make this method acccessible in any view
    helper_method :current_user
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # login
   def create
     # omniauth middleware stores oauth data in the request.env instead of params
     auth = request.env["omniauth.auth"]

     # even though this is a login action, an OAuth login can be a login *or* a registration
     #
     # if the user exists, log her in
     # if the user doesn't exist, create her, then log her in
     user = User.find_by(github_id: auth['uid']) || User.create_from_github(auth)

     session[:user_id] = user.id
     redirect_to root_url, notice: "Signed in!"
   end

   #logout
   def destroy
     reset_session
     redirect_to root_url, notice: "Signed out!"
   end

   def fbcreate
   user = User.from_omniauth(env["omniauth.auth"])
   session[:user_id] = user.id
   redirect_to root_url
  end

  def fbdestroy
   session[:user_id] = nil
   redirect_to root_url
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery

  def new
  end
private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmniauthExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>

  </body>
</html>

app/views/users/new.html.erb
<em><%= notice %></em><br>
<% if current_user %>
  Welcome <%= current_user.name %> you have successfully signed in!<br>
  <%= link_to "Sign out", logout_path %>
<% else %>
  You are so not signed in.<br>
  <%= link_to "Sign in with Github", github_login_path %><br>
<% end %>